// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: validator_proto3.proto

package validatortest

import (
	fmt "fmt"
	_ "github.com/coderyw/go-proto-validators"
	_ "github.com/coderyw/protobuf/gogoproto"
	proto "google.golang.org/protobuf/proto"
	math "math"
	_ "test/pkg2"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
