// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: validator.proto

package validator

import (
	fmt "fmt"
	_ "github.com/coderyw/protobuf/gogoproto"
	proto "github.com/coderyw/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// goTypeName:FieldValidator
type FieldValidator struct {
	// Uses a Golang RE2-syntax regex to match the field contents.
	Regex *string `protobuf:"bytes,1,opt,name=regex" json:"regex,omitempty"`
	// Field value of integer strictly greater than this value.
	IntGt *int64 `protobuf:"varint,2,opt,name=int_gt,json=intGt" json:"int_gt,omitempty"`
	// Field value of integer strictly smaller than this value.
	IntLt *int64 `protobuf:"varint,3,opt,name=int_lt,json=intLt" json:"int_lt,omitempty"`
	// Used for nested message types, requires that the message type exists.
	MsgExists *bool `protobuf:"varint,4,opt,name=msg_exists,json=msgExists" json:"msg_exists,omitempty"`
	// 必填参数，参数非零值
	Required *bool `protobuf:"varint,19,opt,name=required" json:"required,omitempty"`
	// Human error specifies a user-customizable error that is visible to the user.
	HumanError *string `protobuf:"bytes,5,opt,name=human_error,json=humanError" json:"human_error,omitempty"`
	// Field value of double strictly greater than this value.
	// Note that this value can only take on a valid floating point
	// value. Use together with float_epsilon if you need something more specific.
	FloatGt *float64 `protobuf:"fixed64,6,opt,name=float_gt,json=floatGt" json:"float_gt,omitempty"`
	// Field value of double strictly smaller than this value.
	// Note that this value can only take on a valid floating point
	// value. Use together with float_epsilon if you need something more specific.
	FloatLt *float64 `protobuf:"fixed64,7,opt,name=float_lt,json=floatLt" json:"float_lt,omitempty"`
	// Field value of double describing the epsilon within which
	// any comparison should be considered to be true. For example,
	// when using float_gt = 0.35, using a float_epsilon of 0.05
	// would mean that any value above 0.30 is acceptable. It can be
	// thought of as a {float_value_condition} +- {float_epsilon}.
	// If unset, no correction for floating point inaccuracies in
	// comparisons will be attempted.
	FloatEpsilon *float64 `protobuf:"fixed64,8,opt,name=float_epsilon,json=floatEpsilon" json:"float_epsilon,omitempty"`
	// Floating-point value compared to which the field content should be greater or equal.
	FloatGte *float64 `protobuf:"fixed64,9,opt,name=float_gte,json=floatGte" json:"float_gte,omitempty"`
	// Floating-point value compared to which the field content should be smaller or equal.
	FloatLte *float64 `protobuf:"fixed64,10,opt,name=float_lte,json=floatLte" json:"float_lte,omitempty"`
	// Used for string fields, requires the string to be not empty (i.e different from "").
	StringNotEmpty *bool `protobuf:"varint,11,opt,name=string_not_empty,json=stringNotEmpty" json:"string_not_empty,omitempty"`
	// Repeated field with at least this number of elements.
	RepeatedCountMin *int64 `protobuf:"varint,12,opt,name=repeated_count_min,json=repeatedCountMin" json:"repeated_count_min,omitempty"`
	// Repeated field with at most this number of elements.
	RepeatedCountMax *int64 `protobuf:"varint,13,opt,name=repeated_count_max,json=repeatedCountMax" json:"repeated_count_max,omitempty"`
	// Field value of length greater than this value.
	LengthGt *int64 `protobuf:"varint,14,opt,name=length_gt,json=lengthGt" json:"length_gt,omitempty"`
	// Field value of length smaller than this value.
	LengthLt *int64 `protobuf:"varint,15,opt,name=length_lt,json=lengthLt" json:"length_lt,omitempty"`
	// Field value of length strictly equal to this value.
	LengthEq *int64 `protobuf:"varint,16,opt,name=length_eq,json=lengthEq" json:"length_eq,omitempty"`
	// Requires that the value is in the enum.
	IsInEnum *bool `protobuf:"varint,17,opt,name=is_in_enum,json=isInEnum" json:"is_in_enum,omitempty"`
	// Ensures that a string value is in UUID format.
	// uuid_ver specifies the valid UUID versions. Valid values are: 0-5.
	// If uuid_ver is 0 all UUID versions are accepted.
	UuidVer *int32 `protobuf:"varint,18,opt,name=uuid_ver,json=uuidVer" json:"uuid_ver,omitempty"`
	// 字符串长度大于，属于字符串文字长度
	StringLengthGt       *int64             `protobuf:"varint,20,opt,name=string_length_gt,json=stringLengthGt" json:"string_length_gt,omitempty"`
	StringLengthLt       *int64             `protobuf:"varint,21,opt,name=string_length_lt,json=stringLengthLt" json:"string_length_lt,omitempty"`
	StringLengthEq       *int64             `protobuf:"varint,22,opt,name=string_length_eq,json=stringLengthEq" json:"string_length_eq,omitempty"`
	IfField              []*IfieldValidator `protobuf:"bytes,23,rep,name=if_field,json=ifField" json:"if_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FieldValidator) Reset()         { *m = FieldValidator{} }
func (m *FieldValidator) String() string { return proto.CompactTextString(m) }
func (*FieldValidator) ProtoMessage()    {}
func (*FieldValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1c6ec7c0d80dd5, []int{0}
}
func (m *FieldValidator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldValidator.Unmarshal(m, b)
}
func (m *FieldValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldValidator.Marshal(b, m, deterministic)
}
func (m *FieldValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldValidator.Merge(m, src)
}
func (m *FieldValidator) XXX_Size() int {
	return xxx_messageInfo_FieldValidator.Size(m)
}
func (m *FieldValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldValidator.DiscardUnknown(m)
}

var xxx_messageInfo_FieldValidator proto.InternalMessageInfo

func (m *FieldValidator) GetRegex() string {
	if m != nil && m.Regex != nil {
		return *m.Regex
	}
	return ""
}

func (m *FieldValidator) GetIntGt() int64 {
	if m != nil && m.IntGt != nil {
		return *m.IntGt
	}
	return 0
}

func (m *FieldValidator) GetIntLt() int64 {
	if m != nil && m.IntLt != nil {
		return *m.IntLt
	}
	return 0
}

func (m *FieldValidator) GetMsgExists() bool {
	if m != nil && m.MsgExists != nil {
		return *m.MsgExists
	}
	return false
}

func (m *FieldValidator) GetRequired() bool {
	if m != nil && m.Required != nil {
		return *m.Required
	}
	return false
}

func (m *FieldValidator) GetHumanError() string {
	if m != nil && m.HumanError != nil {
		return *m.HumanError
	}
	return ""
}

func (m *FieldValidator) GetFloatGt() float64 {
	if m != nil && m.FloatGt != nil {
		return *m.FloatGt
	}
	return 0
}

func (m *FieldValidator) GetFloatLt() float64 {
	if m != nil && m.FloatLt != nil {
		return *m.FloatLt
	}
	return 0
}

func (m *FieldValidator) GetFloatEpsilon() float64 {
	if m != nil && m.FloatEpsilon != nil {
		return *m.FloatEpsilon
	}
	return 0
}

func (m *FieldValidator) GetFloatGte() float64 {
	if m != nil && m.FloatGte != nil {
		return *m.FloatGte
	}
	return 0
}

func (m *FieldValidator) GetFloatLte() float64 {
	if m != nil && m.FloatLte != nil {
		return *m.FloatLte
	}
	return 0
}

func (m *FieldValidator) GetStringNotEmpty() bool {
	if m != nil && m.StringNotEmpty != nil {
		return *m.StringNotEmpty
	}
	return false
}

func (m *FieldValidator) GetRepeatedCountMin() int64 {
	if m != nil && m.RepeatedCountMin != nil {
		return *m.RepeatedCountMin
	}
	return 0
}

func (m *FieldValidator) GetRepeatedCountMax() int64 {
	if m != nil && m.RepeatedCountMax != nil {
		return *m.RepeatedCountMax
	}
	return 0
}

func (m *FieldValidator) GetLengthGt() int64 {
	if m != nil && m.LengthGt != nil {
		return *m.LengthGt
	}
	return 0
}

func (m *FieldValidator) GetLengthLt() int64 {
	if m != nil && m.LengthLt != nil {
		return *m.LengthLt
	}
	return 0
}

func (m *FieldValidator) GetLengthEq() int64 {
	if m != nil && m.LengthEq != nil {
		return *m.LengthEq
	}
	return 0
}

func (m *FieldValidator) GetIsInEnum() bool {
	if m != nil && m.IsInEnum != nil {
		return *m.IsInEnum
	}
	return false
}

func (m *FieldValidator) GetUuidVer() int32 {
	if m != nil && m.UuidVer != nil {
		return *m.UuidVer
	}
	return 0
}

func (m *FieldValidator) GetStringLengthGt() int64 {
	if m != nil && m.StringLengthGt != nil {
		return *m.StringLengthGt
	}
	return 0
}

func (m *FieldValidator) GetStringLengthLt() int64 {
	if m != nil && m.StringLengthLt != nil {
		return *m.StringLengthLt
	}
	return 0
}

func (m *FieldValidator) GetStringLengthEq() int64 {
	if m != nil && m.StringLengthEq != nil {
		return *m.StringLengthEq
	}
	return 0
}

func (m *FieldValidator) GetIfField() []*IfieldValidator {
	if m != nil {
		return m.IfField
	}
	return nil
}

func (m *FieldValidator) SetRegex_(val string) {
	if m != nil {
		*m.Regex = val
	}

}

func (m *FieldValidator) SetIntGt_(val int64) {
	if m != nil {
		*m.IntGt = val
	}

}

func (m *FieldValidator) SetIntLt_(val int64) {
	if m != nil {
		*m.IntLt = val
	}

}

func (m *FieldValidator) SetMsgExists_(val bool) {
	if m != nil {
		*m.MsgExists = val
	}

}

func (m *FieldValidator) SetRequired_(val bool) {
	if m != nil {
		*m.Required = val
	}

}

func (m *FieldValidator) SetHumanError_(val string) {
	if m != nil {
		*m.HumanError = val
	}

}

func (m *FieldValidator) SetFloatGt_(val float64) {
	if m != nil {
		*m.FloatGt = val
	}

}

func (m *FieldValidator) SetFloatLt_(val float64) {
	if m != nil {
		*m.FloatLt = val
	}

}

func (m *FieldValidator) SetFloatEpsilon_(val float64) {
	if m != nil {
		*m.FloatEpsilon = val
	}

}

func (m *FieldValidator) SetFloatGte_(val float64) {
	if m != nil {
		*m.FloatGte = val
	}

}

func (m *FieldValidator) SetFloatLte_(val float64) {
	if m != nil {
		*m.FloatLte = val
	}

}

func (m *FieldValidator) SetStringNotEmpty_(val bool) {
	if m != nil {
		*m.StringNotEmpty = val
	}

}

func (m *FieldValidator) SetRepeatedCountMin_(val int64) {
	if m != nil {
		*m.RepeatedCountMin = val
	}

}

func (m *FieldValidator) SetRepeatedCountMax_(val int64) {
	if m != nil {
		*m.RepeatedCountMax = val
	}

}

func (m *FieldValidator) SetLengthGt_(val int64) {
	if m != nil {
		*m.LengthGt = val
	}

}

func (m *FieldValidator) SetLengthLt_(val int64) {
	if m != nil {
		*m.LengthLt = val
	}

}

func (m *FieldValidator) SetLengthEq_(val int64) {
	if m != nil {
		*m.LengthEq = val
	}

}

func (m *FieldValidator) SetIsInEnum_(val bool) {
	if m != nil {
		*m.IsInEnum = val
	}

}

func (m *FieldValidator) SetUuidVer_(val int32) {
	if m != nil {
		*m.UuidVer = val
	}

}

func (m *FieldValidator) SetStringLengthGt_(val int64) {
	if m != nil {
		*m.StringLengthGt = val
	}

}

func (m *FieldValidator) SetStringLengthLt_(val int64) {
	if m != nil {
		*m.StringLengthLt = val
	}

}

func (m *FieldValidator) SetStringLengthEq_(val int64) {
	if m != nil {
		*m.StringLengthEq = val
	}

}

func (m *FieldValidator) SetIfField_(val []*IfieldValidator) {
	if m != nil {
		m.IfField = val
	}
	return
}

func (m *FieldValidator) IsNil() bool {
	return m == nil

}

// goTypeName:IfieldValidator
type IfieldValidator struct {
	Field                *string         `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Validator            *JointValidator `protobuf:"bytes,2,opt,name=validator" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *IfieldValidator) Reset()         { *m = IfieldValidator{} }
func (m *IfieldValidator) String() string { return proto.CompactTextString(m) }
func (*IfieldValidator) ProtoMessage()    {}
func (*IfieldValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1c6ec7c0d80dd5, []int{1}
}
func (m *IfieldValidator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IfieldValidator.Unmarshal(m, b)
}
func (m *IfieldValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IfieldValidator.Marshal(b, m, deterministic)
}
func (m *IfieldValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IfieldValidator.Merge(m, src)
}
func (m *IfieldValidator) XXX_Size() int {
	return xxx_messageInfo_IfieldValidator.Size(m)
}
func (m *IfieldValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_IfieldValidator.DiscardUnknown(m)
}

var xxx_messageInfo_IfieldValidator proto.InternalMessageInfo

func (m *IfieldValidator) GetField() string {
	if m != nil && m.Field != nil {
		return *m.Field
	}
	return ""
}

func (m *IfieldValidator) GetValidator() *JointValidator {
	if m != nil {
		return m.Validator
	}
	return nil
}

func (m *IfieldValidator) SetField_(val string) {
	if m != nil {
		*m.Field = val
	}

}

func (m *IfieldValidator) SetValidator_(val *JointValidator) {
	if m != nil {
		m.Validator = val
	}
	return
}

func (m *IfieldValidator) IsNil() bool {
	return m == nil

}

// goTypeName:JointValidator
type JointValidator struct {
	// Uses a Golang RE2-syntax regex to match the field contents.
	Regex *string `protobuf:"bytes,1,opt,name=regex" json:"regex,omitempty"`
	// Field value of integer strictly greater than this value.
	IntGt *int64 `protobuf:"varint,2,opt,name=int_gt,json=intGt" json:"int_gt,omitempty"`
	// Field value of integer strictly smaller than this value.
	IntLt *int64 `protobuf:"varint,3,opt,name=int_lt,json=intLt" json:"int_lt,omitempty"`
	// 整型等于
	IntEq *int64 `protobuf:"varint,22,opt,name=int_eq,json=intEq" json:"int_eq,omitempty"`
	// Used for nested message types, requires that the message type exists.
	MsgExists *bool `protobuf:"varint,4,opt,name=msg_exists,json=msgExists" json:"msg_exists,omitempty"`
	// 必填参数，参数非零值
	Required *bool `protobuf:"varint,5,opt,name=required" json:"required,omitempty"`
	// Field value of double strictly greater than this value.
	// Note that this value can only take on a valid floating point
	// value. Use together with float_epsilon if you need something more specific.
	FloatGt *float64 `protobuf:"fixed64,6,opt,name=float_gt,json=floatGt" json:"float_gt,omitempty"`
	// Field value of double strictly smaller than this value.
	// Note that this value can only take on a valid floating point
	// value. Use together with float_epsilon if you need something more specific.
	FloatLt *float64 `protobuf:"fixed64,7,opt,name=float_lt,json=floatLt" json:"float_lt,omitempty"`
	// Field value of double describing the epsilon within which
	// any comparison should be considered to be true. For example,
	// when using float_gt = 0.35, using a float_epsilon of 0.05
	// would mean that any value above 0.30 is acceptable. It can be
	// thought of as a {float_value_condition} +- {float_epsilon}.
	// If unset, no correction for floating point inaccuracies in
	// comparisons will be attempted.
	FloatEpsilon *float64 `protobuf:"fixed64,8,opt,name=float_epsilon,json=floatEpsilon" json:"float_epsilon,omitempty"`
	// Floating-point value compared to which the field content should be greater or equal.
	FloatGte *float64 `protobuf:"fixed64,9,opt,name=float_gte,json=floatGte" json:"float_gte,omitempty"`
	// Floating-point value compared to which the field content should be smaller or equal.
	FloatLte *float64 `protobuf:"fixed64,10,opt,name=float_lte,json=floatLte" json:"float_lte,omitempty"`
	// Used for string fields, requires the string to be not empty (i.e different from "").
	StringNotEmpty *bool `protobuf:"varint,11,opt,name=string_not_empty,json=stringNotEmpty" json:"string_not_empty,omitempty"`
	// Repeated field with at least this number of elements.
	RepeatedCountMin *int64 `protobuf:"varint,12,opt,name=repeated_count_min,json=repeatedCountMin" json:"repeated_count_min,omitempty"`
	// Repeated field with at most this number of elements.
	RepeatedCountMax *int64 `protobuf:"varint,13,opt,name=repeated_count_max,json=repeatedCountMax" json:"repeated_count_max,omitempty"`
	// Field value of length greater than this value.
	LengthGt *int64 `protobuf:"varint,14,opt,name=length_gt,json=lengthGt" json:"length_gt,omitempty"`
	// Field value of length smaller than this value.
	LengthLt *int64 `protobuf:"varint,15,opt,name=length_lt,json=lengthLt" json:"length_lt,omitempty"`
	// Field value of length strictly equal to this value.
	LengthEq *int64 `protobuf:"varint,16,opt,name=length_eq,json=lengthEq" json:"length_eq,omitempty"`
	// 字符串长度大于，属于字符串文字长度
	StringLengthGt *int64 `protobuf:"varint,18,opt,name=string_length_gt,json=stringLengthGt" json:"string_length_gt,omitempty"`
	StringLengthLt *int64 `protobuf:"varint,19,opt,name=string_length_lt,json=stringLengthLt" json:"string_length_lt,omitempty"`
	StringLengthEq *int64 `protobuf:"varint,20,opt,name=string_length_eq,json=stringLengthEq" json:"string_length_eq,omitempty"`
	// 字符串等于
	StringEq             *string  `protobuf:"bytes,21,opt,name=string_eq,json=stringEq" json:"string_eq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JointValidator) Reset()         { *m = JointValidator{} }
func (m *JointValidator) String() string { return proto.CompactTextString(m) }
func (*JointValidator) ProtoMessage()    {}
func (*JointValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1c6ec7c0d80dd5, []int{2}
}
func (m *JointValidator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JointValidator.Unmarshal(m, b)
}
func (m *JointValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JointValidator.Marshal(b, m, deterministic)
}
func (m *JointValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JointValidator.Merge(m, src)
}
func (m *JointValidator) XXX_Size() int {
	return xxx_messageInfo_JointValidator.Size(m)
}
func (m *JointValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_JointValidator.DiscardUnknown(m)
}

var xxx_messageInfo_JointValidator proto.InternalMessageInfo

func (m *JointValidator) GetRegex() string {
	if m != nil && m.Regex != nil {
		return *m.Regex
	}
	return ""
}

func (m *JointValidator) GetIntGt() int64 {
	if m != nil && m.IntGt != nil {
		return *m.IntGt
	}
	return 0
}

func (m *JointValidator) GetIntLt() int64 {
	if m != nil && m.IntLt != nil {
		return *m.IntLt
	}
	return 0
}

func (m *JointValidator) GetIntEq() int64 {
	if m != nil && m.IntEq != nil {
		return *m.IntEq
	}
	return 0
}

func (m *JointValidator) GetMsgExists() bool {
	if m != nil && m.MsgExists != nil {
		return *m.MsgExists
	}
	return false
}

func (m *JointValidator) GetRequired() bool {
	if m != nil && m.Required != nil {
		return *m.Required
	}
	return false
}

func (m *JointValidator) GetFloatGt() float64 {
	if m != nil && m.FloatGt != nil {
		return *m.FloatGt
	}
	return 0
}

func (m *JointValidator) GetFloatLt() float64 {
	if m != nil && m.FloatLt != nil {
		return *m.FloatLt
	}
	return 0
}

func (m *JointValidator) GetFloatEpsilon() float64 {
	if m != nil && m.FloatEpsilon != nil {
		return *m.FloatEpsilon
	}
	return 0
}

func (m *JointValidator) GetFloatGte() float64 {
	if m != nil && m.FloatGte != nil {
		return *m.FloatGte
	}
	return 0
}

func (m *JointValidator) GetFloatLte() float64 {
	if m != nil && m.FloatLte != nil {
		return *m.FloatLte
	}
	return 0
}

func (m *JointValidator) GetStringNotEmpty() bool {
	if m != nil && m.StringNotEmpty != nil {
		return *m.StringNotEmpty
	}
	return false
}

func (m *JointValidator) GetRepeatedCountMin() int64 {
	if m != nil && m.RepeatedCountMin != nil {
		return *m.RepeatedCountMin
	}
	return 0
}

func (m *JointValidator) GetRepeatedCountMax() int64 {
	if m != nil && m.RepeatedCountMax != nil {
		return *m.RepeatedCountMax
	}
	return 0
}

func (m *JointValidator) GetLengthGt() int64 {
	if m != nil && m.LengthGt != nil {
		return *m.LengthGt
	}
	return 0
}

func (m *JointValidator) GetLengthLt() int64 {
	if m != nil && m.LengthLt != nil {
		return *m.LengthLt
	}
	return 0
}

func (m *JointValidator) GetLengthEq() int64 {
	if m != nil && m.LengthEq != nil {
		return *m.LengthEq
	}
	return 0
}

func (m *JointValidator) GetStringLengthGt() int64 {
	if m != nil && m.StringLengthGt != nil {
		return *m.StringLengthGt
	}
	return 0
}

func (m *JointValidator) GetStringLengthLt() int64 {
	if m != nil && m.StringLengthLt != nil {
		return *m.StringLengthLt
	}
	return 0
}

func (m *JointValidator) GetStringLengthEq() int64 {
	if m != nil && m.StringLengthEq != nil {
		return *m.StringLengthEq
	}
	return 0
}

func (m *JointValidator) GetStringEq() string {
	if m != nil && m.StringEq != nil {
		return *m.StringEq
	}
	return ""
}

func (m *JointValidator) SetRegex_(val string) {
	if m != nil {
		*m.Regex = val
	}

}

func (m *JointValidator) SetIntGt_(val int64) {
	if m != nil {
		*m.IntGt = val
	}

}

func (m *JointValidator) SetIntLt_(val int64) {
	if m != nil {
		*m.IntLt = val
	}

}

func (m *JointValidator) SetIntEq_(val int64) {
	if m != nil {
		*m.IntEq = val
	}

}

func (m *JointValidator) SetMsgExists_(val bool) {
	if m != nil {
		*m.MsgExists = val
	}

}

func (m *JointValidator) SetRequired_(val bool) {
	if m != nil {
		*m.Required = val
	}

}

func (m *JointValidator) SetFloatGt_(val float64) {
	if m != nil {
		*m.FloatGt = val
	}

}

func (m *JointValidator) SetFloatLt_(val float64) {
	if m != nil {
		*m.FloatLt = val
	}

}

func (m *JointValidator) SetFloatEpsilon_(val float64) {
	if m != nil {
		*m.FloatEpsilon = val
	}

}

func (m *JointValidator) SetFloatGte_(val float64) {
	if m != nil {
		*m.FloatGte = val
	}

}

func (m *JointValidator) SetFloatLte_(val float64) {
	if m != nil {
		*m.FloatLte = val
	}

}

func (m *JointValidator) SetStringNotEmpty_(val bool) {
	if m != nil {
		*m.StringNotEmpty = val
	}

}

func (m *JointValidator) SetRepeatedCountMin_(val int64) {
	if m != nil {
		*m.RepeatedCountMin = val
	}

}

func (m *JointValidator) SetRepeatedCountMax_(val int64) {
	if m != nil {
		*m.RepeatedCountMax = val
	}

}

func (m *JointValidator) SetLengthGt_(val int64) {
	if m != nil {
		*m.LengthGt = val
	}

}

func (m *JointValidator) SetLengthLt_(val int64) {
	if m != nil {
		*m.LengthLt = val
	}

}

func (m *JointValidator) SetLengthEq_(val int64) {
	if m != nil {
		*m.LengthEq = val
	}

}

func (m *JointValidator) SetStringLengthGt_(val int64) {
	if m != nil {
		*m.StringLengthGt = val
	}

}

func (m *JointValidator) SetStringLengthLt_(val int64) {
	if m != nil {
		*m.StringLengthLt = val
	}

}

func (m *JointValidator) SetStringLengthEq_(val int64) {
	if m != nil {
		*m.StringLengthEq = val
	}

}

func (m *JointValidator) SetStringEq_(val string) {
	if m != nil {
		*m.StringEq = val
	}

}

func (m *JointValidator) IsNil() bool {
	return m == nil

}

// goTypeName:OneofValidator
type OneofValidator struct {
	// Require that one of the oneof fields is set.
	Required             *bool    `protobuf:"varint,1,opt,name=required" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneofValidator) Reset()         { *m = OneofValidator{} }
func (m *OneofValidator) String() string { return proto.CompactTextString(m) }
func (*OneofValidator) ProtoMessage()    {}
func (*OneofValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1c6ec7c0d80dd5, []int{3}
}
func (m *OneofValidator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OneofValidator.Unmarshal(m, b)
}
func (m *OneofValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OneofValidator.Marshal(b, m, deterministic)
}
func (m *OneofValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneofValidator.Merge(m, src)
}
func (m *OneofValidator) XXX_Size() int {
	return xxx_messageInfo_OneofValidator.Size(m)
}
func (m *OneofValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_OneofValidator.DiscardUnknown(m)
}

var xxx_messageInfo_OneofValidator proto.InternalMessageInfo

func (m *OneofValidator) GetRequired() bool {
	if m != nil && m.Required != nil {
		return *m.Required
	}
	return false
}

func (m *OneofValidator) SetRequired_(val bool) {
	if m != nil {
		*m.Required = val
	}

}

func (m *OneofValidator) IsNil() bool {
	return m == nil

}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FieldOptions)(nil),
	ExtensionType: (*FieldValidator)(nil),
	Field:         65020,
	Name:          "validator.field",
	Tag:           "bytes,65020,opt,name=field",
	Filename:      "validator.proto",
}

var E_Oneof = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.OneofOptions)(nil),
	ExtensionType: (*OneofValidator)(nil),
	Field:         65021,
	Name:          "validator.oneof",
	Tag:           "bytes,65021,opt,name=oneof",
	Filename:      "validator.proto",
}

func init() {
	proto.RegisterType((*FieldValidator)(nil), "validator.FieldValidator")
	proto.RegisterType((*IfieldValidator)(nil), "validator.IfieldValidator")
	proto.RegisterType((*JointValidator)(nil), "validator.JointValidator")
	proto.RegisterType((*OneofValidator)(nil), "validator.OneofValidator")
	proto.RegisterExtension(E_Field)
	proto.RegisterExtension(E_Oneof)
}

func init() { proto.RegisterFile("validator.proto", fileDescriptor_bf1c6ec7c0d80dd5) }

var fileDescriptor_bf1c6ec7c0d80dd5 = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x95, 0xcf, 0x6e, 0xd3, 0x4a,
	0x18, 0xc5, 0xaf, 0x6f, 0x6e, 0x1a, 0x67, 0xd2, 0xa6, 0xbd, 0xd3, 0x16, 0xa6, 0x29, 0x85, 0x28,
	0x6c, 0xbc, 0x68, 0x13, 0x54, 0x09, 0x90, 0x60, 0x07, 0x32, 0x55, 0x51, 0xa0, 0xc8, 0x8b, 0x2e,
	0xd8, 0x18, 0x37, 0x1e, 0xbb, 0x23, 0xd9, 0x33, 0xf1, 0xf8, 0x73, 0x49, 0xdf, 0x82, 0x77, 0xe1,
	0x91, 0x78, 0x01, 0xf6, 0x80, 0x84, 0x3c, 0xfe, 0x9b, 0xc6, 0x8b, 0x22, 0x21, 0x56, 0xac, 0xea,
	0x39, 0xe7, 0xe8, 0xf8, 0xeb, 0x97, 0xf9, 0xc9, 0x68, 0xf3, 0xca, 0x09, 0x98, 0xeb, 0x80, 0x90,
	0xe3, 0xb9, 0x14, 0x20, 0x70, 0xb7, 0x14, 0x06, 0x43, 0x5f, 0x08, 0x3f, 0xa0, 0x13, 0x65, 0x5c,
	0x24, 0xde, 0xc4, 0xa5, 0xf1, 0x4c, 0xb2, 0x79, 0x19, 0x1e, 0x0c, 0xd4, 0x9f, 0x89, 0x2f, 0x7c,
	0x51, 0x3d, 0x65, 0xde, 0xe8, 0xd3, 0x1a, 0xea, 0xbf, 0x62, 0x34, 0x70, 0xcf, 0x8b, 0x42, 0xbc,
	0x83, 0xda, 0x92, 0xfa, 0x74, 0x41, 0xb4, 0xa1, 0x66, 0x74, 0xad, 0xec, 0x80, 0x77, 0xd1, 0x1a,
	0xe3, 0x60, 0xfb, 0x40, 0xfe, 0x1d, 0x6a, 0x46, 0xcb, 0x6a, 0x33, 0x0e, 0x27, 0x50, 0xc8, 0x01,
	0x90, 0x56, 0x29, 0x4f, 0x01, 0x1f, 0x20, 0x14, 0xc6, 0xbe, 0x4d, 0x17, 0x2c, 0x86, 0x98, 0xfc,
	0x37, 0xd4, 0x0c, 0xdd, 0xea, 0x86, 0xb1, 0x6f, 0x2a, 0x01, 0x0f, 0x90, 0x2e, 0x69, 0x94, 0x30,
	0x49, 0x5d, 0xb2, 0xad, 0xcc, 0xf2, 0x8c, 0x1f, 0xa0, 0xde, 0x65, 0x12, 0x3a, 0xdc, 0xa6, 0x52,
	0x0a, 0x49, 0xda, 0x6a, 0x08, 0xa4, 0x24, 0x33, 0x55, 0xf0, 0x1e, 0xd2, 0xbd, 0x40, 0x38, 0x6a,
	0x96, 0xb5, 0xa1, 0x66, 0x68, 0x56, 0x47, 0x9d, 0x4f, 0xa0, 0xb2, 0x02, 0x20, 0x9d, 0x9a, 0x35,
	0x05, 0xfc, 0x10, 0x6d, 0x64, 0x16, 0x9d, 0xc7, 0x2c, 0x10, 0x9c, 0xe8, 0xca, 0x5f, 0x57, 0xa2,
	0x99, 0x69, 0x78, 0x1f, 0x75, 0x8b, 0x6a, 0x4a, 0xba, 0x2a, 0xa0, 0xe7, 0xdd, 0xb4, 0x32, 0x03,
	0xa0, 0x04, 0xd5, 0xcc, 0x29, 0x50, 0x6c, 0xa0, 0xad, 0x18, 0x24, 0xe3, 0xbe, 0xcd, 0x05, 0xd8,
	0x34, 0x9c, 0xc3, 0x35, 0xe9, 0xa9, 0xff, 0xac, 0x9f, 0xe9, 0x6f, 0x05, 0x98, 0xa9, 0x8a, 0x0f,
	0x11, 0x96, 0x74, 0x4e, 0x1d, 0xa0, 0xae, 0x3d, 0x13, 0x09, 0x07, 0x3b, 0x64, 0x9c, 0xac, 0xab,
	0xed, 0x6d, 0x15, 0xce, 0xcb, 0xd4, 0x78, 0xc3, 0x78, 0x53, 0xda, 0x59, 0x90, 0x8d, 0xa6, 0xb4,
	0xb3, 0x48, 0x47, 0x0c, 0x28, 0xf7, 0xe1, 0x32, 0xdd, 0x4d, 0x5f, 0x85, 0xf4, 0x4c, 0x38, 0x81,
	0x9a, 0x19, 0x00, 0xd9, 0xac, 0x9b, 0xd3, 0xba, 0x49, 0x23, 0xb2, 0x55, 0x37, 0xcd, 0x08, 0xdf,
	0x43, 0x88, 0xc5, 0x36, 0xe3, 0x36, 0xe5, 0x49, 0x48, 0xfe, 0xcf, 0x7e, 0x30, 0x16, 0x9f, 0x72,
	0x93, 0x27, 0x61, 0xba, 0xf4, 0x24, 0x61, 0xae, 0x7d, 0x45, 0x25, 0xc1, 0x43, 0xcd, 0x68, 0x5b,
	0x9d, 0xf4, 0x7c, 0x4e, 0x65, 0x6d, 0x2b, 0xd5, 0x58, 0x3b, 0xaa, 0x3c, 0xdf, 0xca, 0xb4, 0x18,
	0x6e, 0x25, 0x19, 0x00, 0xd9, 0x5d, 0x4d, 0x4e, 0x1b, 0x92, 0x34, 0x22, 0x77, 0x56, 0x93, 0x66,
	0x84, 0x1f, 0x23, 0x9d, 0x79, 0xb6, 0x97, 0xde, 0x6e, 0x72, 0x77, 0xd8, 0x32, 0x7a, 0xc7, 0x83,
	0x71, 0x05, 0xd2, 0xa9, 0xb7, 0x74, 0xed, 0xad, 0x0e, 0xf3, 0x14, 0x08, 0xa3, 0x0f, 0x68, 0xf3,
	0x86, 0x97, 0x22, 0x91, 0xd5, 0xe4, 0x48, 0xa8, 0x03, 0x7e, 0x8a, 0x2a, 0x0c, 0x15, 0x15, 0xbd,
	0xe3, 0xbd, 0xda, 0x0b, 0x5e, 0x0b, 0xc6, 0xa1, 0xea, 0xaf, 0xb2, 0xa3, 0xcf, 0x6d, 0xd4, 0x5f,
	0x76, 0x7f, 0x0b, 0x74, 0xb9, 0x5c, 0xee, 0x23, 0x95, 0xcd, 0xe8, 0x57, 0x58, 0x6c, 0xdf, 0x60,
	0xf1, 0x2f, 0x6a, 0x7f, 0x1a, 0xb5, 0x26, 0x62, 0xf0, 0xad, 0x89, 0xd9, 0xbe, 0x35, 0x31, 0x3b,
	0x8d, 0xc4, 0xec, 0xa3, 0x6e, 0x9e, 0xa4, 0x91, 0xc2, 0xaf, 0x6b, 0xe9, 0x99, 0x60, 0x46, 0xa3,
	0x43, 0xd4, 0x3f, 0xe3, 0x54, 0x78, 0xd5, 0xa5, 0xad, 0x5f, 0x1d, 0x6d, 0xf9, 0xea, 0x3c, 0x7b,
	0x97, 0x23, 0x83, 0x0f, 0xc6, 0xd9, 0x07, 0x6a, 0x5c, 0x7c, 0xa0, 0xc6, 0x0a, 0xb3, 0xb3, 0x39,
	0x30, 0xc1, 0x63, 0xf2, 0xfd, 0x5b, 0x6b, 0x85, 0x9c, 0xe5, 0x0f, 0x52, 0x8e, 0x5b, 0xda, 0x28,
	0xd2, 0xf7, 0x37, 0x34, 0xaa, 0xb9, 0x8a, 0xc6, 0x1f, 0x0d, 0x8d, 0xcb, 0x83, 0x5b, 0x59, 0xd1,
	0x8b, 0x27, 0x5f, 0xbf, 0xdc, 0xff, 0xe7, 0xfd, 0x23, 0x9f, 0xc1, 0x65, 0x72, 0x31, 0x9e, 0x89,
	0x70, 0x32, 0x13, 0x2e, 0x95, 0xd7, 0x1f, 0x27, 0xbe, 0x38, 0x52, 0xe5, 0x47, 0x65, 0x45, 0xfc,
	0xbc, 0x7c, 0xfc, 0x19, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x6e, 0xae, 0x54, 0x8f, 0x07, 0x00, 0x00,
}
