// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: nested.proto

package validator_examples

import (
	fmt "fmt"
	_ "github.com/coderyw/go-proto-validators"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
